### ISSUE TITLE
SolrExpress v.5

### ISSUE THREAD

**Issue by diegobrum** [solr-express/solr-express#187]
Some things to do:

- [x] Remove DI engine from core package (#188)
 - **Goals**
  1. Avoid **\#IFDEF**
  2. Avoid bugs like #186
 - **Pros**
  1. Possibility to use favorite DI engine of user
  2. Code maintenance
 - **Cons**
  1. More packages in references
---
- [x] Improve performance
 - Newtonsoft performance (#171)
 - New responses (#135)
---
- [x] Rename package *SolrExpress.Core* to *SolrExpress* to avoid confusions with suffix *.Core* with .Net Core (#189)
---
- [ ] Async support
 1. HttpConnection using async (#161)
 2. DocumentCollection executions
---
- [x] New way to translate queries to Solr 4/5/6 (#190)
 - **Goals**
  1. Less code
  2. Less unit test
  3. Easier to understand
  4. Easier to create new parsers
---
- [x] New way to inform Parameter Values (#191)
 - **Goals**
  1. Easier to understand
  2. Implements feature like #162
  3. Easier to use
---
- [x] New way to configure Parameters (#195)
 - **Goals**
  1. Easier to understand
  2. Easier to use

**Comment by stanuku** [comment]
@diegobrum: I can help on some of these, let me know.

**Comment by stanuku** [comment]
@diegobrum is 4.2 milestone complete? are you planning to create a branch for 5.0?

**Comment by diegobrum** [comment]
@stanuku  yep :)

**Comment by diegobrum** [comment]
@stanuku Please, take a look in this code

https://github.com/solr-express/solr-express/tree/23c4acabd14ee30adc5289ddd5dc6de1d0ac362a

Very first draft of v5

Any thoughts?

**Comment by stanuku** [comment]
@diegobrum: I have looked at the code briefly. Looks fine so far.
